/*
 * This file is generated by jOOQ.
 */
package com.kenvix.commenter.dao.jooq;


import com.kenvix.commenter.dao.jooq.tables.Post;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>commentserver</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index POST_PRIMARY = Indexes0.POST_PRIMARY;
    public static final Index POST_TITLE = Indexes0.POST_TITLE;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index POST_PRIMARY = Internal.createIndex("PRIMARY", Post.POST, new OrderField[] { Post.POST.POSTID }, true);
        public static Index POST_TITLE = Internal.createIndex("title", Post.POST, new OrderField[] { Post.POST.TITLE }, true);
    }
}
