/*
 * This file is generated by jOOQ.
 */
package com.kenvix.commenter.dao.jooq;


import com.kenvix.commenter.dao.jooq.tables.Post;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in commentserver
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>commentserver.post</code>.
     */
    public static final Post POST = com.kenvix.commenter.dao.jooq.tables.Post.POST;
}
